### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by bateman** [yashsmehta/personality-prediction#2]
Cloned from GH, installed requirements, executed `LM_extractor.py` as specified in the `README.md` file. Got this.
```
$ python LM_extractor.py -dataset_type 'essays' -token_length 512 -batch_size 32 -embed 'bert-base' -op_dir 'pkl_data'

running on cpu
essays : bert-base : 512 : 512_head : cls
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 433/433 [00:00<00:00, 101kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████| 440M/440M [00:13<00:00, 33.8MB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████| 232k/232k [00:00<00:00, 492kB/s]
Traceback (most recent call last):
  File "LM_extractor.py", line 111, in <module>
    map_dataset = MyMapDataset(dataset, tokenizer, token_length, DEVICE, mode)
  File "/Users/fabio/git/personality-prediction/utils/data_utils.py", line 18, in __init__
    author_ids, input_ids, targets = dataset_processors.essays_embeddings(datafile, tokenizer, token_length, mode)
  File "/Users/fabio/git/personality-prediction/utils/dataset_processors.py", line 59, in essays_embeddings
    df = load_essays_df(datafile)
  File "/Users/fabio/git/personality-prediction/utils/dataset_processors.py", line 27, in load_essays_df
    with open(datafile, "rt") as csvf:
FileNotFoundError: [Errno 2] No such file or directory: '../data/essays/essays.csv'
```

Yet a small file is present in `data/essays/essays.csv`. Please, advise.

**Comment by bobkosse** [comment]
If you run the command from the readme file 
```
python LM_extractor.py -dataset_type 'essays' -token_length 512 -datafile 'data/essays.csv' -batch_size 32 -embed 'bert-base' -op_dir 'pkl_data'
```
you have to change the ```-datafile``` parameter to ```data/essays/essays.csv```

**Comment by yashsmehta** [comment]
> If you run the command from the readme file
> 
> ```
> python LM_extractor.py -dataset_type 'essays' -token_length 512 -datafile 'data/essays.csv' -batch_size 32 -embed 'bert-base' -op_dir 'pkl_data'
> ```
> 
> you have to change the `-datafile` parameter to `data/essays/essays.csv`

this should work - although let us know if you're still having trouble running the code and we'll try to help.

**Comment by JenniferTanH** [comment]
But LM_extractor.py does not have an argument called -datafile
